### ISSUE TITLE
Release artifacts to Maven Central

### ISSUE THREAD

**Issue by michael-o** [bgandon/juli-to-slf4j#2]
Hey there, unfortunately your project is not on Maven Central. I do use Tomcat JDBC in a few standalone tools which require JULI, but I do use SLF4J + Logback. It's essential to have this on Maven Central.

**Comment by bgandon** [comment]
Well, indeed. You're right, I should push an artefact to Maven Central.
I keep you updated.

**Comment by bgandon** [comment]
Ok, I've slightly updated the project, and the request for a maven repo [is created](https://issues.sonatype.org/browse/OSSRH-32474)

Once the request si treated, the new version `1.1.1` will be uploaded to Maven Central.

**Comment by bgandon** [comment]
The new version `1.1.1` is deployed to Sonatype OSS repo hosting, and [I asked](https://issues.sonatype.org/browse/OSSRH-32474?focusedCommentId=415472&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-415472) for them to push it to Maven Central.

**Comment by bgandon** [comment]
[There it is](http://search.maven.org/#artifactdetails%7Corg.gandon.tomcat%7Cjuli-to-slf4j%7C1.1.1%7Cjar), available on Maven Central!
