### ISSUE TITLE
Fails to build with Javadoc 8

### ISSUE THREAD

**Issue by michael-o** [bgandon/juli-to-slf4j#3]
`mvn javadoc:jar`:

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (default-cli
    ) on project juli-to-slf4j: MavenReportException: Error while generating Javadoc:
    [ERROR] Exit code: 1 - D:\Projekte\juli-to-slf4j-juli-to-slf4j-1.1.0\src\main\java\org\apache\juli\l
    ogging\impl\SLF4JDelegatingLog.java:56: error: reference not found
    [ERROR]  * Instances delegate to {@link a PreBootstrapLogger}s that store all
    [ERROR]                                 ^
    [ERROR] D:\Projekte\juli-to-slf4j-juli-to-slf4j-1.1.0\src\main\java\org\apache\juli\logging\impl\SLF
    4JDelegatingLog.java:79: error: reference not found
    [ERROR]  * {@link LocationAwareLogger} interface. The default is {@link #WARN_INT},
    [ERROR]                                                                 ^
    [ERROR] D:\Projekte\juli-to-slf4j-juli-to-slf4j-1.1.0\src\main\java\org\apache\juli\logging\impl\SLF
    4JDelegatingLog.java:88: warning - Tag @link: can't find WARN_INT in org.apache.juli.logging.impl.SL
    F4JDelegatingLog
    [ERROR] D:\Projekte\juli-to-slf4j-juli-to-slf4j-1.1.0\src\main\java\org\slf4j\LoggerFactory.java:401
    : error: self-closing element not allowed
    [ERROR]      * <p/>
    [ERROR]        ^
    [ERROR] D:\Projekte\juli-to-slf4j-juli-to-slf4j-1.1.0\src\main\java\org\slf4j\LoggerFactory.java:401
    : warning: empty <p> tag
    [ERROR]      * <p/>
    [ERROR]        ^
    [ERROR] D:\Projekte\juli-to-slf4j-juli-to-slf4j-1.1.0\src\main\java\org\slf4j\LoggerFactory.java:402
    : error: self-closing element not allowed
    [ERROR]      * <p/>
    [ERROR]        ^
    [ERROR] D:\Projekte\juli-to-slf4j-juli-to-slf4j-1.1.0\src\main\java\org\slf4j\LoggerFactory.java:85:
     warning: empty <p> tag
    [ERROR]  * <p>
    [ERROR]    ^
    [ERROR] D:\Projekte\juli-to-slf4j-juli-to-slf4j-1.1.0\src\main\java\org\slf4j\LoggerFactory.java:88:
     error: reference not found
    [ERROR]  * logging. Other implementations such as {@link org.slf4j.impl.NOPLogger
    [ERROR]                                                  ^
    [ERROR] D:\Projekte\juli-to-slf4j-juli-to-slf4j-1.1.0\src\main\java\org\slf4j\LoggerFactory.java:89:
     error: reference not found
    [ERROR]  * NOPLogger} and {@link org.slf4j.impl.SimpleLogger SimpleLogger} are also
    [ERROR]                          ^
    [ERROR]
    [ERROR] Command line was: "C:\Program Files\Java\jdk1.8.0_131\jre\..\bin\javadoc.exe" @options @packages
    [ERROR]
    [ERROR] Refer to the generated Javadoc files in 'D:\Projekte\juli-to-slf4j-juli-to-slf4j-1.1.0\targe
    t\apidocs' dir.
    [ERROR]
    [ERROR] -> [Help 1]
    [ERROR]
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR]
    [ERROR] For more information about the errors and possible solutions, please read the following arti
    cles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by bgandon** [comment]
Ok, thanks for the report.
I need to have a look at that indeed.
I keep you updated.

**Comment by bgandon** [comment]
Ok, this is fixed in the new version 1.1.1.

Publishing to Maven Central is currently being done.
